<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "si_news"
 *
 * Auto generated by Extension Builder 2016-01-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Si News',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Pera',
	'author_email' => 'pera91@mykolab.ch',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'news' => '4.0.0-4.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);